# syntax=docker/dockerfile:experimental

# Sample command
#   docker run -p 8081:8081 -e "JAVA_OPTS=-Ddebug -Xmx128m" cool-app --server.port=8081

FROM adoptopenjdk:11-jdk-hotspot AS build
WORKDIR /app
COPY .mvn .mvn
COPY mvnw mvnw
# Copy pom.xml and install dependencies
COPY pom.xml .
# --mount=type=cache will populate cache on first run or for 'docker build ... --no-cache', and re-use otherwise
RUN --mount=type=cache,target=/root/.m2 ./mvnw dependency:go-offline
# Copy source and build artifact
COPY src/ src/
RUN ./mvnw clean package -DskipTests

FROM adoptopenjdk:11-jre-hotspot
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
USER 1002
ENTRYPOINT ["sh", "-c", "exec java ${JAVA_OPTS} -jar app.jar ${0} ${@}"]


############################################
## Alternative, using distroless base image:
## Sample command
##   docker run -p 8081:8081 -e "JAVA_TOOL_OPTIONS=-Ddebug -Xmx128m" cool-app /app.jar --server.port=8081
#
#FROM gcr.io/distroless/java:11
#WORKDIR /app
#COPY --from=build /app/target/*.jar app.jar
#USER nonroot
#CMD ["app.jar"]
############################################
