# syntax=docker/dockerfile:experimental

# Sample command
#   docker run -p 8081:8081 -e "JAVA_TOOL_OPTIONS=-Ddebug -Xmx128m" cool-app --server.port=8081

ARG JAVA_VERSION=11
ARG MAVEN_VERSION=3.6.3

FROM maven:${MAVEN_VERSION}-jdk-${JAVA_VERSION}-openj9 AS build
WORKDIR /app
COPY pom.xml .
RUN --mount=type=cache,target=/root/.m2 mvn dependency:go-offline
COPY src/ src/
RUN mvn clean package -DskipTests -P layered
WORKDIR /app/target/dependency
RUN mkdir -p dependencies spring-boot-loader snapshot-dependencies application \
    && java -Djarmode=layertools -jar ../*.jar extract

FROM gcr.io/distroless/java:${JAVA_VERSION}
WORKDIR /app
ARG DEPENDENCY=/app/target/dependency
COPY --from=build ${DEPENDENCY}/dependencies/ .
COPY --from=build ${DEPENDENCY}/spring-boot-loader/ .
COPY --from=build ${DEPENDENCY}/snapshot-dependencies/ .
COPY --from=build ${DEPENDENCY}/application/ .
USER nonroot
ENTRYPOINT ["java", "-cp", ".:lib/*", "org.springframework.boot.loader.JarLauncher"]

