FROM maven:3.6.3-jdk-11-openj9 AS build
WORKDIR /app
# Copy pom.xml and install dependencies
COPY pom.xml .
RUN mvn dependency:go-offline
# Copy source and build artifact
COPY src/ src/
RUN mvn clean package -DskipTests
WORKDIR /app/target/dependency
RUN jar -xf ../*.jar

FROM gcr.io/distroless/java:11
ARG DEPENDENCY=/app/target/dependency
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build ${DEPENDENCY}/org /app/org
COPY --from=build ${DEPENDENCY}/BOOT-INF/classes /app
ENTRYPOINT ["java", "-cp", "app:app/lib/*", "org.springframework.boot.loader.JarLauncher"]
# Or for faster startup, specify main application class, comment out COPY to /app/org and use:
#ENTRYPOINT ["java", "-cp", "app:app/lib/*", "io.pivotal.coolapp.CoolAppApplication"]


# To run with JVM options and command-line args:
#   docker run -p 8081:8081 -e "JAVA_TOOL_OPTIONS=-Ddebug -Xmx128m" cool-app --server.port=8081
#   http localhost:8081 # In a different window
#   <Ctrl+C> in container process window to stop container

