# Set a non-root user after copying files to image
# Use a numeric user id for simplicity
# Observe that non-root user does not have write privileges outside of /tmp
# Observe that COPY executed as root always; use --chown flag to change ownership

FROM adoptopenjdk:11-jre-hotspot
WORKDIR /app
COPY target/*.jar app.jar
USER 1002
ENTRYPOINT ["sh", "-c", "exec java ${JAVA_OPTS} -jar app.jar ${0} ${@}"]

