# syntax=docker/dockerfile:experimental

# Sample command
#   docker run -p 8081:8081 -e "JAVA_OPTS=-Ddebug -Xmx128m" cool-app --server.port=8081

FROM adoptopenjdk:11-jdk-hotspot AS build
WORKDIR /app
COPY .mvn .mvn
COPY mvnw mvnw
COPY pom.xml .
COPY src/ src/
RUN --mount=type=bind,source=./.m2/repository,target=/root/.m2/repository,rw ./mvnw clean package -DskipTests -P layered
WORKDIR /app/target/dependency
# Can delete RUN mkdir line starting with Spring Boot 2.3.0.RC1
RUN mkdir -p dependencies spring-boot-loader snapshot-dependencies application \
    && java -Djarmode=layertools -jar ../*.jar extract

FROM adoptopenjdk:11-jre-hotspot
WORKDIR /app
ARG DEPENDENCY=/app/target/dependency
COPY --from=build ${DEPENDENCY}/dependencies/ .
COPY --from=build ${DEPENDENCY}/spring-boot-loader/ .
COPY --from=build ${DEPENDENCY}/snapshot-dependencies/ .
COPY --from=build ${DEPENDENCY}/application/ .
USER 1002
ENTRYPOINT ["sh", "-c", "exec java ${JAVA_OPTS} -cp .:lib/* org.springframework.boot.loader.JarLauncher ${0} ${@}"]

