FROM maven:3.6.3-jdk-11-openj9 AS build
WORKDIR /app
# Copy pom.xml and install dependencies
COPY pom.xml .
RUN mvn dependency:go-offline
# Copy source and build artifact
COPY src/ src/
RUN mvn clean package -DskipTests -P layered
WORKDIR /app/target/dependency
# Use mkdir to ensure all dirs exist so that COPY operation in next stage succeeds
# Spring Boot 2.3.0.RC1 will correct this issue and make sure all dirs exist, even if empty
RUN mkdir -p dependencies spring-boot-loader snapshot-dependencies application \
    && java -Djarmode=layertools -jar ../*.jar extract

FROM adoptopenjdk:11-jre-hotspot
ARG DEPENDENCY=/app/target/dependency
COPY --from=build ${DEPENDENCY}/dependencies/ ./app
COPY --from=build ${DEPENDENCY}/spring-boot-loader/ ./app
COPY --from=build ${DEPENDENCY}/snapshot-dependencies/ ./app
COPY --from=build ${DEPENDENCY}/application/ ./app
ENTRYPOINT ["sh", "-c", "exec java ${JAVA_OPTS} -cp app:app/lib/* org.springframework.boot.loader.JarLauncher ${0} ${@}"]

