# Make sure .dockerignore does not exclude target/cool-app-1.0.0.jar
# Set entrypoint to support:
#   - Ctrl+C to kill container locally ("exec java" vs "java")
#   - Accept JAVA_OPTS from command line
#   - Accept command line arguments (e.g. --server.port=8081)

FROM adoptopenjdk:11-jre-hotspot
COPY target/*.jar app.jar
ENTRYPOINT ["sh", "-c", "exec java ${JAVA_OPTS} -jar /app.jar ${0} ${@}"]


# To run with JVM options and command-line args:
#   docker run -p 8081:8081 -e "JAVA_OPTS=-Ddebug -Xmx128m" cool-app --server.port=8081
# OR
#   docker run -p 8081:8081 -e "JAVA_TOOL_OPTIONS=-Ddebug -Xmx128m" cool-app --server.port=8081
#   http localhost:8081 # In a different window
#   <Ctrl+C> in container process window to stop container

