# Make sure .dockerignore does not exclude target/cool-app-1.0.0.jar
# Set entrypoint to support:
#   - Ctrl+C to kill container locally ("exec java" vs "java")
#   - Accept JAVA_OPTS from command line
#   - Accept command line arguments (e.g. --server.port=8081)
#   e.g. The following command works:
#   docker run -p 8080:8081 -e "JAVA_OPTS=-Ddebug -Xmx128m" cool-app:cmd --server.port=8081

FROM adoptopenjdk:11-jre-hotspot
COPY target/*.jar app.jar
#ENTRYPOINT ["sh", "-c", "exec java ${JAVA_OPTS} -jar /app.jar ${0} ${@}"]
# Alternative ENTRYPOINT using script:
RUN echo "#!/bin/sh" > run.sh && \
    echo "exec java ${JAVA_OPTS} -jar /app.jar ${@}" >> run.sh && \
    chmod +x run.sh
ENTRYPOINT ["./run.sh"]

