# Set a non-root user after copying files to image
# Use a numeric user id for simplicity
# Observe that non-root user does not have write privileges outside of /tmp
# Observe that COPY executed as root always; use --chown flag to change ownership

FROM adoptopenjdk:11-jre-hotspot
WORKDIR /app
USER 1002
RUN touch /app/user_file || true;   # Expecting failure
RUN touch /tmp/user_file || true;   # Expecting success
COPY target/*.jar app.jar
RUN echo "app files:" && ls -ltra /app && \
    echo "tmp files:" && ls -ltra /tmp
ENTRYPOINT ["sh", "-c", "exec java ${JAVA_OPTS} -jar app.jar ${0} ${@}"]

