# syntax=docker/dockerfile:experimental

ARG JAVA_VERSION=11
ARG MAVEN_VERSION=3.6.3

FROM maven:${MAVEN_VERSION}-jdk-${JAVA_VERSION}-openj9 AS build
WORKDIR /app
COPY pom.xml .
RUN --mount=type=cache,target=/root/.m2 \
    ./mvnw dependency:go-offline
COPY src/ src/
RUN --mount=type=cache,target=/root/.m2 \
    ./mvnw clean package -DskipTests --offline -P layered
WORKDIR /app/target/dependency
RUN java -Djarmode=layertools -jar ../*.jar extract
# Temporary workaround to open issue
RUN mkdir -p snapshot-dependencies

FROM gcr.io/distroless/java:${JAVA_VERSION} AS release
LABEL org.opencontainers.image.authors="me@example.com"
WORKDIR /app
ARG DEPENDENCY=/app/target/dependency
COPY --from=build ${DEPENDENCY}/dependencies/ .
COPY --from=build ${DEPENDENCY}/spring-boot-loader/ .
COPY --from=build ${DEPENDENCY}/snapshot-dependencies/ .
COPY --from=build ${DEPENDENCY}/application/ .
USER nonroot
ENTRYPOINT ["java", "-cp", ".:lib/*", "org.springframework.boot.loader.JarLauncher"]
