# syntax=docker/dockerfile:experimental

FROM adoptopenjdk:11-jdk-hotspot AS build
WORKDIR /app
COPY .mvn .mvn
COPY mvnw mvnw
COPY pom.xml .
RUN --mount=type=cache,target=/root/.m2 \
    ./mvnw dependency:go-offline
COPY src/ src/
RUN --mount=type=cache,target=/root/.m2 \
    ./mvnw clean package -DskipTests --offline
WORKDIR /app/target/dependency
RUN java -Djarmode=layertools -jar ../*.jar extract
# Temporary workaround to open issue
RUN mkdir -p snapshot-dependencies

FROM adoptopenjdk:11-jre-hotspot AS release
LABEL org.opencontainers.image.authors="me@example.com"
WORKDIR /app
ARG DEPENDENCY=/app/target/dependency
COPY --from=build ${DEPENDENCY}/dependencies/ .
COPY --from=build ${DEPENDENCY}/spring-boot-loader/ .
COPY --from=build ${DEPENDENCY}/snapshot-dependencies/ .
COPY --from=build ${DEPENDENCY}/application/ .
USER 1002
ENTRYPOINT ["sh", "-c", "exec java ${JAVA_OPTS} -cp .:lib/* org.springframework.boot.loader.JarLauncher ${0} ${@}"]
